added Contacts entity, dao and tests
mosgjig/swim pull request #3
Opened 2016-12-08 19:41 UTC by vlerac

2016-12-08 19:48 UTC, durimkryeziu requested changes
Should remove everything .idea/ because these are IntelliJ IDEA files that you IDE auto generated for you and no one of us need these!

Also should not commit and push your very own database properties like "password: 1234"

Also do not commit swim.iml, this one also is a file autogenerated by your IDE

Folder target/ should NEVER get committed

2016-12-09 09:55 UTC, mosgjig requested changes
namely you included things that were not supposed to be included.  Also the db pwd.

2016-12-09 09:55 UTC, mosgjig commented on src/main/java/org/prnhs/javaee/swim/core/entity/Contacts.java
> +
no need for spacing here.

2016-12-09 09:55 UTC, mosgjig commented on src/main/java/org/prnhs/javaee/swim/core/entity/User.java
> -import java.util.Objects;
don't include unnecessary changes.

2016-12-09 09:55 UTC, mosgjig commented on src/main/resources/application.yml
> +        password: 1234
this will break other peoples build.  Assure your mysql pwd is root, or keep this change localy just for yourself.

2016-12-09 09:55 UTC, mosgjig commented on src/test/java/org/prnhs/javaee/swim/core/dao/UserDaoIT.java
>  import org.junit.Before;
unnecessary changes.

2016-12-09 09:55 UTC, mosgjig commented on target/classes/application.yml
> +spring:
don't include target folder.  ignore it on update.  Use your ide to tag the directory as ignored or not included in commit.

2016-12-15 19:25 UTC, closed without merging