mq - dozer
mosgjig/swim pull request #49
Opened 2017-01-11 20:39 UTC by MirlindQeriqi

Mapper applied in ProgramService
ProgramTranslator deleted

2017-01-12 09:02 UTC, mosgjig approved these changes

2017-01-12 09:02 UTC, mosgjig commented
Did you run your service test?  they should be broken, and will have to mock the mapper now.

2017-01-12 09:03 UTC, mosgjig commented
I closed it on accident.  Please address the unit tests for service and re-open.

2017-01-12 09:58 UTC, MirlindQeriqi commented
Yeah, I didn't run the service test. And now that I did I can see they're broken. Lemme work on it and I'll commit the changes

2017-01-16 18:34 UTC, mosgjig requested changes

2017-01-16 18:34 UTC, mosgjig commented on src/main/java/org/prnhs/javaee/swim/services/config/MapperConfig.java
> +                        .fields(field("id"), field("key"), oneWay())
use constants please :)

2017-01-16 19:52 UTC, mosgjig approved these changes

2017-01-16 19:52 UTC, merged